### ISSUE TITLE
Block chain service init is not working with learn-chaincode version 1.0

### ISSUE THREAD

**Issue by diptimanchakrabarti** [IBM-Blockchain/ibm-blockchain-issues#79]
Getting issue on Bluemix Blockchain service. I have used hyperledger febric version 5.0 and code is compatible with that. Is Bluemix is usnign V6.0 of Hyperledger febric.

The input json format is : {
  "jsonrpc": "2.0",
  "method": "deploy",
  "params": {
    "type": 1,
    "chaincodeID": {
      "path": "https://github.com/diptimanchakrabarti/learn-chaincode/start"
    },
    "ctorMsg": {
      "function": "Init",
      "args": [
        "Good Morning"
      ]
    },
    "secureContext": "user_type1_0"
  },
  "id": 0
}
Output received with error:
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32001,
    "message": "Deployment failure",
    "data": "Error when deploying chaincode: Error getting chaincode package bytes: Error getting code 'go get' failed with error: \"exit status 2\"\n# github.com/diptimanchakrabarti/learn-chaincode/start\n/opt/gopath/_usercode_/122828921/src/github.com/diptimanchakrabarti/learn-chaincode/start/chaincode_start.go:34: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:\n\t*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)\n\t\thave Init(*shim.ChaincodeStub, string, []string) ([]byte, error)\n\t\twant Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)\n"
  },
  "id": 0
}

**Comment by mrshah-at-work** [comment]
Yes, the new bluemix blockchain services use fabric v0.6

**Comment by dhyey20** [comment]
@diptimanchakrabarti Please try porting the code to v0.6, the bluemix service is running the hyperledger fabric v0.6 code as @mrshah-at-ibm mentioned. Closing this. Feel free to reopen it if you are still seeing issues.
